//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIM.Web.Admin.JobServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:trackable-entities:service", ConfigurationName="JobServiceReference.IJobService")]
    public interface IJobService {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IJobService/GetJobsList", ReplyAction="urn:trackable-entities:service/IJobService/GetJobsListResponse")]
        AIM.Service.Entities.Models.Job[] GetJobsList();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IJobService/GetJob", ReplyAction="urn:trackable-entities:service/IJobService/GetJobResponse")]
        AIM.Service.Entities.Models.Job GetJob(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IJobService/UpdateJob", ReplyAction="urn:trackable-entities:service/IJobService/UpdateJobResponse")]
        AIM.Service.Entities.Models.Job UpdateJob(AIM.Service.Entities.Models.Job entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IJobService/CreateJob", ReplyAction="urn:trackable-entities:service/IJobService/CreateJobResponse")]
        AIM.Service.Entities.Models.Job CreateJob(AIM.Service.Entities.Models.Job entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IJobService/DeleteJob", ReplyAction="urn:trackable-entities:service/IJobService/DeleteJobResponse")]
        bool DeleteJob(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IJobService/GetOpenJobs", ReplyAction="urn:trackable-entities:service/IJobService/GetOpenJobsResponse")]
        AIM.Service.Entities.Models.OpenJob[] GetOpenJobs();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IJobService/GetStoreList", ReplyAction="urn:trackable-entities:service/IJobService/GetStoreListResponse")]
        AIM.Service.Entities.Models.Store[] GetStoreList(System.Nullable<int> regionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IJobService/GetRegionList", ReplyAction="urn:trackable-entities:service/IJobService/GetRegionListResponse")]
        AIM.Service.Entities.Models.Region[] GetRegionList();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IJobService/GetOpenJobsForStore", ReplyAction="urn:trackable-entities:service/IJobService/GetOpenJobsForStoreResponse")]
        AIM.Service.Entities.Models.OpenJob[] GetOpenJobsForStore(System.Nullable<int> storeId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJobServiceChannel : AIM.Web.Admin.JobServiceReference.IJobService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JobServiceClient : System.ServiceModel.ClientBase<AIM.Web.Admin.JobServiceReference.IJobService>, AIM.Web.Admin.JobServiceReference.IJobService {
        
        public JobServiceClient() {
        }
        
        public JobServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JobServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AIM.Service.Entities.Models.Job[] GetJobsList() {
            return base.Channel.GetJobsList();
        }
        
        public AIM.Service.Entities.Models.Job GetJob(System.Nullable<int> id) {
            return base.Channel.GetJob(id);
        }
        
        public AIM.Service.Entities.Models.Job UpdateJob(AIM.Service.Entities.Models.Job entity) {
            return base.Channel.UpdateJob(entity);
        }
        
        public AIM.Service.Entities.Models.Job CreateJob(AIM.Service.Entities.Models.Job entity) {
            return base.Channel.CreateJob(entity);
        }
        
        public bool DeleteJob(int id) {
            return base.Channel.DeleteJob(id);
        }
        
        public AIM.Service.Entities.Models.OpenJob[] GetOpenJobs() {
            return base.Channel.GetOpenJobs();
        }
        
        public AIM.Service.Entities.Models.Store[] GetStoreList(System.Nullable<int> regionId) {
            return base.Channel.GetStoreList(regionId);
        }
        
        public AIM.Service.Entities.Models.Region[] GetRegionList() {
            return base.Channel.GetRegionList();
        }
        
        public AIM.Service.Entities.Models.OpenJob[] GetOpenJobsForStore(System.Nullable<int> storeId) {
            return base.Channel.GetOpenJobsForStore(storeId);
        }
    }
}
