//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIM.Web.Application.JobServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:trackable-entities:service", ConfigurationName="JobServiceReference.IJobService")]
    public interface IJobService {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IJobService/GetJobsList", ReplyAction="urn:trackable-entities:service/IJobService/GetJobsListResponse")]
        AIM.Application.Service.Entities.Models.Job[] GetJobsList();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IJobService/GetOpenJobsList", ReplyAction="urn:trackable-entities:service/IJobService/GetOpenJobsListResponse")]
        AIM.Application.Service.Entities.Models.OpenJob[] GetOpenJobsList(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IJobService/GetJob", ReplyAction="urn:trackable-entities:service/IJobService/GetJobResponse")]
        AIM.Application.Service.Entities.Models.Job GetJob(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IJobService/GetOpenJob", ReplyAction="urn:trackable-entities:service/IJobService/GetOpenJobResponse")]
        AIM.Application.Service.Entities.Models.OpenJob GetOpenJob(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IJobService/UpdateJob", ReplyAction="urn:trackable-entities:service/IJobService/UpdateJobResponse")]
        AIM.Application.Service.Entities.Models.Job UpdateJob(AIM.Application.Service.Entities.Models.Job entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IJobService/CreateJob", ReplyAction="urn:trackable-entities:service/IJobService/CreateJobResponse")]
        AIM.Application.Service.Entities.Models.Job CreateJob(AIM.Application.Service.Entities.Models.Job entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IJobService/DeleteJob", ReplyAction="urn:trackable-entities:service/IJobService/DeleteJobResponse")]
        bool DeleteJob(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IJobService/GetRegionList", ReplyAction="urn:trackable-entities:service/IJobService/GetRegionListResponse")]
        AIM.Application.Service.Entities.Models.Region[] GetRegionList();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IJobService/GetRegionName", ReplyAction="urn:trackable-entities:service/IJobService/GetRegionNameResponse")]
        string GetRegionName(System.Nullable<int> id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IJobServiceChannel : AIM.Web.Application.JobServiceReference.IJobService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JobServiceClient : System.ServiceModel.ClientBase<AIM.Web.Application.JobServiceReference.IJobService>, AIM.Web.Application.JobServiceReference.IJobService {
        
        public JobServiceClient() {
        }
        
        public JobServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JobServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JobServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AIM.Application.Service.Entities.Models.Job[] GetJobsList() {
            return base.Channel.GetJobsList();
        }
        
        public AIM.Application.Service.Entities.Models.OpenJob[] GetOpenJobsList(System.Nullable<int> id) {
            return base.Channel.GetOpenJobsList(id);
        }
        
        public AIM.Application.Service.Entities.Models.Job GetJob(System.Nullable<int> id) {
            return base.Channel.GetJob(id);
        }
        
        public AIM.Application.Service.Entities.Models.OpenJob GetOpenJob(System.Nullable<int> id) {
            return base.Channel.GetOpenJob(id);
        }
        
        public AIM.Application.Service.Entities.Models.Job UpdateJob(AIM.Application.Service.Entities.Models.Job entity) {
            return base.Channel.UpdateJob(entity);
        }
        
        public AIM.Application.Service.Entities.Models.Job CreateJob(AIM.Application.Service.Entities.Models.Job entity) {
            return base.Channel.CreateJob(entity);
        }
        
        public bool DeleteJob(int id) {
            return base.Channel.DeleteJob(id);
        }
        
        public AIM.Application.Service.Entities.Models.Region[] GetRegionList() {
            return base.Channel.GetRegionList();
        }
        
        public string GetRegionName(System.Nullable<int> id) {
            return base.Channel.GetRegionName(id);
        }
    }
}
