//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackableEntities.Models
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/TrackableEntities.Models", IsReference=true)]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private TrackableEntities.Models.Applicant ApplicantField;
        
        private TrackableEntities.Models.Employee EmployeeField;
        
        private string[] ModifiedPropertiesField;
        
        private TrackableEntities.Models.PersonalInfo PersonalInfoField;
        
        private System.Nullable<int> PersonalInfoIDField;
        
        private TrackableEntities.TrackingState TrackingStateField;
        
        private int UserIDField;
        
        private System.Nullable<int> applicantIDField;
        
        private System.Nullable<int> applicationIDField;
        
        private string emailField;
        
        private System.Nullable<int> employeeIDField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string middleNameField;
        
        private string passwordField;
        
        private string passwordCoderField;
        
        private System.Nullable<decimal> socialSecurityNumberField;
        
        private string socialSecurityNumberCoderField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.Models.Applicant Applicant
        {
            get
            {
                return this.ApplicantField;
            }
            set
            {
                this.ApplicantField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.Models.Employee Employee
        {
            get
            {
                return this.EmployeeField;
            }
            set
            {
                this.EmployeeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ModifiedProperties
        {
            get
            {
                return this.ModifiedPropertiesField;
            }
            set
            {
                this.ModifiedPropertiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.Models.PersonalInfo PersonalInfo
        {
            get
            {
                return this.PersonalInfoField;
            }
            set
            {
                this.PersonalInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PersonalInfoID
        {
            get
            {
                return this.PersonalInfoIDField;
            }
            set
            {
                this.PersonalInfoIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.TrackingState TrackingState
        {
            get
            {
                return this.TrackingStateField;
            }
            set
            {
                this.TrackingStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> applicantID
        {
            get
            {
                return this.applicantIDField;
            }
            set
            {
                this.applicantIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> applicationID
        {
            get
            {
                return this.applicationIDField;
            }
            set
            {
                this.applicationIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> employeeID
        {
            get
            {
                return this.employeeIDField;
            }
            set
            {
                this.employeeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string middleName
        {
            get
            {
                return this.middleNameField;
            }
            set
            {
                this.middleNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string passwordCoder
        {
            get
            {
                return this.passwordCoderField;
            }
            set
            {
                this.passwordCoderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> socialSecurityNumber
        {
            get
            {
                return this.socialSecurityNumberField;
            }
            set
            {
                this.socialSecurityNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string socialSecurityNumberCoder
        {
            get
            {
                return this.socialSecurityNumberCoderField;
            }
            set
            {
                this.socialSecurityNumberCoderField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Applicant", Namespace="http://schemas.datacontract.org/2004/07/TrackableEntities.Models", IsReference=true)]
    public partial class Applicant : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private TrackableEntities.Models.ApplicantQuestionAnswer[] ApplicantQuestionAnswersField;
        
        private TrackableEntities.Models.Application[] ApplicationsField;
        
        private TrackableEntities.Models.Education[] EducationsField;
        
        private TrackableEntities.Models.Hour[] HoursField;
        
        private TrackableEntities.Models.JobHistory[] JobHistoriesField;
        
        private string[] ModifiedPropertiesField;
        
        private TrackableEntities.Models.Reference[] ReferencesField;
        
        private TrackableEntities.TrackingState TrackingStateField;
        
        private TrackableEntities.Models.User[] UsersField;
        
        private System.Nullable<int> answerIDField;
        
        private int applicantIDField;
        
        private System.Nullable<int> applicationIDField;
        
        private System.Nullable<int> educationIDField;
        
        private System.Nullable<int> hoursIDField;
        
        private System.Nullable<int> jobHistoryIDField;
        
        private System.Nullable<int> referenceIDField;
        
        private System.Nullable<int> userIDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.Models.ApplicantQuestionAnswer[] ApplicantQuestionAnswers
        {
            get
            {
                return this.ApplicantQuestionAnswersField;
            }
            set
            {
                this.ApplicantQuestionAnswersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.Models.Application[] Applications
        {
            get
            {
                return this.ApplicationsField;
            }
            set
            {
                this.ApplicationsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.Models.Education[] Educations
        {
            get
            {
                return this.EducationsField;
            }
            set
            {
                this.EducationsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.Models.Hour[] Hours
        {
            get
            {
                return this.HoursField;
            }
            set
            {
                this.HoursField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.Models.JobHistory[] JobHistories
        {
            get
            {
                return this.JobHistoriesField;
            }
            set
            {
                this.JobHistoriesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ModifiedProperties
        {
            get
            {
                return this.ModifiedPropertiesField;
            }
            set
            {
                this.ModifiedPropertiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.Models.Reference[] References
        {
            get
            {
                return this.ReferencesField;
            }
            set
            {
                this.ReferencesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.TrackingState TrackingState
        {
            get
            {
                return this.TrackingStateField;
            }
            set
            {
                this.TrackingStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.Models.User[] Users
        {
            get
            {
                return this.UsersField;
            }
            set
            {
                this.UsersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> answerID
        {
            get
            {
                return this.answerIDField;
            }
            set
            {
                this.answerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int applicantID
        {
            get
            {
                return this.applicantIDField;
            }
            set
            {
                this.applicantIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> applicationID
        {
            get
            {
                return this.applicationIDField;
            }
            set
            {
                this.applicationIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> educationID
        {
            get
            {
                return this.educationIDField;
            }
            set
            {
                this.educationIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> hoursID
        {
            get
            {
                return this.hoursIDField;
            }
            set
            {
                this.hoursIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> jobHistoryID
        {
            get
            {
                return this.jobHistoryIDField;
            }
            set
            {
                this.jobHistoryIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> referenceID
        {
            get
            {
                return this.referenceIDField;
            }
            set
            {
                this.referenceIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> userID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://schemas.datacontract.org/2004/07/TrackableEntities.Models", IsReference=true)]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private TrackableEntities.Models.Job JobField;
        
        private string[] ModifiedPropertiesField;
        
        private TrackableEntities.TrackingState TrackingStateField;
        
        private TrackableEntities.Models.User[] UsersField;
        
        private int employeeIDField;
        
        private System.Nullable<int> jobIDField;
        
        private System.Nullable<int> permissionsIDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.Models.Job Job
        {
            get
            {
                return this.JobField;
            }
            set
            {
                this.JobField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ModifiedProperties
        {
            get
            {
                return this.ModifiedPropertiesField;
            }
            set
            {
                this.ModifiedPropertiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.TrackingState TrackingState
        {
            get
            {
                return this.TrackingStateField;
            }
            set
            {
                this.TrackingStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.Models.User[] Users
        {
            get
            {
                return this.UsersField;
            }
            set
            {
                this.UsersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int employeeID
        {
            get
            {
                return this.employeeIDField;
            }
            set
            {
                this.employeeIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> jobID
        {
            get
            {
                return this.jobIDField;
            }
            set
            {
                this.jobIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> permissionsID
        {
            get
            {
                return this.permissionsIDField;
            }
            set
            {
                this.permissionsIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonalInfo", Namespace="http://schemas.datacontract.org/2004/07/TrackableEntities.Models", IsReference=true)]
    public partial class PersonalInfo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string[] ModifiedPropertiesField;
        
        private int PersonalInfoIDField;
        
        private TrackableEntities.TrackingState TrackingStateField;
        
        private TrackableEntities.Models.User[] UsersField;
        
        private string aliasField;
        
        private string cityField;
        
        private System.Nullable<decimal> phoneField;
        
        private string streetField;
        
        private string street2Field;
        
        private System.Nullable<int> userIDField;
        
        private System.Nullable<decimal> zipField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ModifiedProperties
        {
            get
            {
                return this.ModifiedPropertiesField;
            }
            set
            {
                this.ModifiedPropertiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PersonalInfoID
        {
            get
            {
                return this.PersonalInfoIDField;
            }
            set
            {
                this.PersonalInfoIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.TrackingState TrackingState
        {
            get
            {
                return this.TrackingStateField;
            }
            set
            {
                this.TrackingStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.Models.User[] Users
        {
            get
            {
                return this.UsersField;
            }
            set
            {
                this.UsersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string alias
        {
            get
            {
                return this.aliasField;
            }
            set
            {
                this.aliasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string city
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string street
        {
            get
            {
                return this.streetField;
            }
            set
            {
                this.streetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string street2
        {
            get
            {
                return this.street2Field;
            }
            set
            {
                this.street2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> userID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> zip
        {
            get
            {
                return this.zipField;
            }
            set
            {
                this.zipField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApplicantQuestionAnswer", Namespace="http://schemas.datacontract.org/2004/07/TrackableEntities.Models", IsReference=true)]
    public partial class ApplicantQuestionAnswer : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private TrackableEntities.Models.Applicant ApplicantField;
        
        private string[] ModifiedPropertiesField;
        
        private TrackableEntities.Models.Question QuestionField;
        
        private TrackableEntities.TrackingState TrackingStateField;
        
        private int answerIDField;
        
        private string answerStringField;
        
        private System.Nullable<int> applicantIDField;
        
        private System.Nullable<int> quesitonIDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.Models.Applicant Applicant
        {
            get
            {
                return this.ApplicantField;
            }
            set
            {
                this.ApplicantField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ModifiedProperties
        {
            get
            {
                return this.ModifiedPropertiesField;
            }
            set
            {
                this.ModifiedPropertiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.Models.Question Question
        {
            get
            {
                return this.QuestionField;
            }
            set
            {
                this.QuestionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.TrackingState TrackingState
        {
            get
            {
                return this.TrackingStateField;
            }
            set
            {
                this.TrackingStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int answerID
        {
            get
            {
                return this.answerIDField;
            }
            set
            {
                this.answerIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string answerString
        {
            get
            {
                return this.answerStringField;
            }
            set
            {
                this.answerStringField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> applicantID
        {
            get
            {
                return this.applicantIDField;
            }
            set
            {
                this.applicantIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> quesitonID
        {
            get
            {
                return this.quesitonIDField;
            }
            set
            {
                this.quesitonIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Application", Namespace="http://schemas.datacontract.org/2004/07/TrackableEntities.Models", IsReference=true)]
    public partial class Application : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private TrackableEntities.Models.Applicant ApplicantField;
        
        private TrackableEntities.Models.Job JobField;
        
        private string[] ModifiedPropertiesField;
        
        private TrackableEntities.TrackingState TrackingStateField;
        
        private System.Nullable<int> applicantIDField;
        
        private int applicationIDField;
        
        private System.Nullable<System.DateTime> dateCreatedField;
        
        private System.Nullable<int> jobIDField;
        
        private string preEmploymentStatementField;
        
        private int statusField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.Models.Applicant Applicant
        {
            get
            {
                return this.ApplicantField;
            }
            set
            {
                this.ApplicantField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.Models.Job Job
        {
            get
            {
                return this.JobField;
            }
            set
            {
                this.JobField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ModifiedProperties
        {
            get
            {
                return this.ModifiedPropertiesField;
            }
            set
            {
                this.ModifiedPropertiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.TrackingState TrackingState
        {
            get
            {
                return this.TrackingStateField;
            }
            set
            {
                this.TrackingStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> applicantID
        {
            get
            {
                return this.applicantIDField;
            }
            set
            {
                this.applicantIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int applicationID
        {
            get
            {
                return this.applicationIDField;
            }
            set
            {
                this.applicationIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> dateCreated
        {
            get
            {
                return this.dateCreatedField;
            }
            set
            {
                this.dateCreatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> jobID
        {
            get
            {
                return this.jobIDField;
            }
            set
            {
                this.jobIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string preEmploymentStatement
        {
            get
            {
                return this.preEmploymentStatementField;
            }
            set
            {
                this.preEmploymentStatementField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Education", Namespace="http://schemas.datacontract.org/2004/07/TrackableEntities.Models", IsReference=true)]
    public partial class Education : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private TrackableEntities.Models.Applicant ApplicantField;
        
        private string[] ModifiedPropertiesField;
        
        private TrackableEntities.TrackingState TrackingStateField;
        
        private System.Nullable<int> applicantIDField;
        
        private string cityField;
        
        private string degreeField;
        
        private int educationIDField;
        
        private System.Nullable<System.DateTime> graduatedField;
        
        private string schoolNameField;
        
        private string stateField;
        
        private string streetField;
        
        private string street2Field;
        
        private string yearsAttendedField;
        
        private System.Nullable<decimal> zipField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.Models.Applicant Applicant
        {
            get
            {
                return this.ApplicantField;
            }
            set
            {
                this.ApplicantField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ModifiedProperties
        {
            get
            {
                return this.ModifiedPropertiesField;
            }
            set
            {
                this.ModifiedPropertiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.TrackingState TrackingState
        {
            get
            {
                return this.TrackingStateField;
            }
            set
            {
                this.TrackingStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> applicantID
        {
            get
            {
                return this.applicantIDField;
            }
            set
            {
                this.applicantIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string city
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string degree
        {
            get
            {
                return this.degreeField;
            }
            set
            {
                this.degreeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int educationID
        {
            get
            {
                return this.educationIDField;
            }
            set
            {
                this.educationIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> graduated
        {
            get
            {
                return this.graduatedField;
            }
            set
            {
                this.graduatedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string schoolName
        {
            get
            {
                return this.schoolNameField;
            }
            set
            {
                this.schoolNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string street
        {
            get
            {
                return this.streetField;
            }
            set
            {
                this.streetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string street2
        {
            get
            {
                return this.street2Field;
            }
            set
            {
                this.street2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string yearsAttended
        {
            get
            {
                return this.yearsAttendedField;
            }
            set
            {
                this.yearsAttendedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> zip
        {
            get
            {
                return this.zipField;
            }
            set
            {
                this.zipField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hour", Namespace="http://schemas.datacontract.org/2004/07/TrackableEntities.Models", IsReference=true)]
    public partial class Hour : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private TrackableEntities.Models.Applicant ApplicantField;
        
        private TrackableEntities.Models.Job[] JobsField;
        
        private string[] ModifiedPropertiesField;
        
        private TrackableEntities.TrackingState TrackingStateField;
        
        private System.Nullable<int> applicantIDField;
        
        private System.Nullable<System.TimeSpan> friCloseField;
        
        private System.Nullable<System.TimeSpan> friOpenField;
        
        private int hoursIDField;
        
        private System.Nullable<System.TimeSpan> monCloseField;
        
        private System.Nullable<System.TimeSpan> monOpenField;
        
        private System.Nullable<System.TimeSpan> satCloseField;
        
        private System.Nullable<System.TimeSpan> satOpenField;
        
        private System.Nullable<System.TimeSpan> sunCloseField;
        
        private System.Nullable<System.TimeSpan> sunOpenField;
        
        private System.Nullable<System.TimeSpan> thursCloseField;
        
        private System.Nullable<System.TimeSpan> thursOpenField;
        
        private System.Nullable<System.TimeSpan> tueCloseField;
        
        private System.Nullable<System.TimeSpan> tueOpenField;
        
        private System.Nullable<System.TimeSpan> wedCloseField;
        
        private System.Nullable<System.TimeSpan> wedOpenField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.Models.Applicant Applicant
        {
            get
            {
                return this.ApplicantField;
            }
            set
            {
                this.ApplicantField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.Models.Job[] Jobs
        {
            get
            {
                return this.JobsField;
            }
            set
            {
                this.JobsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ModifiedProperties
        {
            get
            {
                return this.ModifiedPropertiesField;
            }
            set
            {
                this.ModifiedPropertiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.TrackingState TrackingState
        {
            get
            {
                return this.TrackingStateField;
            }
            set
            {
                this.TrackingStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> applicantID
        {
            get
            {
                return this.applicantIDField;
            }
            set
            {
                this.applicantIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> friClose
        {
            get
            {
                return this.friCloseField;
            }
            set
            {
                this.friCloseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> friOpen
        {
            get
            {
                return this.friOpenField;
            }
            set
            {
                this.friOpenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int hoursID
        {
            get
            {
                return this.hoursIDField;
            }
            set
            {
                this.hoursIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> monClose
        {
            get
            {
                return this.monCloseField;
            }
            set
            {
                this.monCloseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> monOpen
        {
            get
            {
                return this.monOpenField;
            }
            set
            {
                this.monOpenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> satClose
        {
            get
            {
                return this.satCloseField;
            }
            set
            {
                this.satCloseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> satOpen
        {
            get
            {
                return this.satOpenField;
            }
            set
            {
                this.satOpenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> sunClose
        {
            get
            {
                return this.sunCloseField;
            }
            set
            {
                this.sunCloseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> sunOpen
        {
            get
            {
                return this.sunOpenField;
            }
            set
            {
                this.sunOpenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> thursClose
        {
            get
            {
                return this.thursCloseField;
            }
            set
            {
                this.thursCloseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> thursOpen
        {
            get
            {
                return this.thursOpenField;
            }
            set
            {
                this.thursOpenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> tueClose
        {
            get
            {
                return this.tueCloseField;
            }
            set
            {
                this.tueCloseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> tueOpen
        {
            get
            {
                return this.tueOpenField;
            }
            set
            {
                this.tueOpenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> wedClose
        {
            get
            {
                return this.wedCloseField;
            }
            set
            {
                this.wedCloseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.TimeSpan> wedOpen
        {
            get
            {
                return this.wedOpenField;
            }
            set
            {
                this.wedOpenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="JobHistory", Namespace="http://schemas.datacontract.org/2004/07/TrackableEntities.Models", IsReference=true)]
    public partial class JobHistory : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private TrackableEntities.Models.Applicant ApplicantField;
        
        private string[] ModifiedPropertiesField;
        
        private TrackableEntities.TrackingState TrackingStateField;
        
        private System.Nullable<int> applicantIDField;
        
        private string cityField;
        
        private System.Nullable<System.DateTime> dateFromField;
        
        private System.Nullable<System.DateTime> dateToField;
        
        private string employerNameField;
        
        private System.Nullable<decimal> endingSalaryField;
        
        private int jobHistoryIDField;
        
        private System.Nullable<decimal> phoneField;
        
        private string positionField;
        
        private string reasonForLeavingField;
        
        private string responsibilitiesField;
        
        private System.Nullable<decimal> startingSalaryField;
        
        private string stateField;
        
        private string streetField;
        
        private string street2Field;
        
        private string supervisorField;
        
        private System.Nullable<decimal> zipField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.Models.Applicant Applicant
        {
            get
            {
                return this.ApplicantField;
            }
            set
            {
                this.ApplicantField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ModifiedProperties
        {
            get
            {
                return this.ModifiedPropertiesField;
            }
            set
            {
                this.ModifiedPropertiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.TrackingState TrackingState
        {
            get
            {
                return this.TrackingStateField;
            }
            set
            {
                this.TrackingStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> applicantID
        {
            get
            {
                return this.applicantIDField;
            }
            set
            {
                this.applicantIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string city
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> dateFrom
        {
            get
            {
                return this.dateFromField;
            }
            set
            {
                this.dateFromField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> dateTo
        {
            get
            {
                return this.dateToField;
            }
            set
            {
                this.dateToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string employerName
        {
            get
            {
                return this.employerNameField;
            }
            set
            {
                this.employerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> endingSalary
        {
            get
            {
                return this.endingSalaryField;
            }
            set
            {
                this.endingSalaryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int jobHistoryID
        {
            get
            {
                return this.jobHistoryIDField;
            }
            set
            {
                this.jobHistoryIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string reasonForLeaving
        {
            get
            {
                return this.reasonForLeavingField;
            }
            set
            {
                this.reasonForLeavingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string responsibilities
        {
            get
            {
                return this.responsibilitiesField;
            }
            set
            {
                this.responsibilitiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> startingSalary
        {
            get
            {
                return this.startingSalaryField;
            }
            set
            {
                this.startingSalaryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string street
        {
            get
            {
                return this.streetField;
            }
            set
            {
                this.streetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string street2
        {
            get
            {
                return this.street2Field;
            }
            set
            {
                this.street2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string supervisor
        {
            get
            {
                return this.supervisorField;
            }
            set
            {
                this.supervisorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> zip
        {
            get
            {
                return this.zipField;
            }
            set
            {
                this.zipField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reference", Namespace="http://schemas.datacontract.org/2004/07/TrackableEntities.Models", IsReference=true)]
    public partial class Reference : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private TrackableEntities.Models.Applicant ApplicantField;
        
        private string[] ModifiedPropertiesField;
        
        private TrackableEntities.TrackingState TrackingStateField;
        
        private System.Nullable<int> applicantIDField;
        
        private string refCompanyField;
        
        private string refFullNameField;
        
        private System.Nullable<decimal> refPhoneField;
        
        private string refTitleField;
        
        private int referenceIDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.Models.Applicant Applicant
        {
            get
            {
                return this.ApplicantField;
            }
            set
            {
                this.ApplicantField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ModifiedProperties
        {
            get
            {
                return this.ModifiedPropertiesField;
            }
            set
            {
                this.ModifiedPropertiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.TrackingState TrackingState
        {
            get
            {
                return this.TrackingStateField;
            }
            set
            {
                this.TrackingStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> applicantID
        {
            get
            {
                return this.applicantIDField;
            }
            set
            {
                this.applicantIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string refCompany
        {
            get
            {
                return this.refCompanyField;
            }
            set
            {
                this.refCompanyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string refFullName
        {
            get
            {
                return this.refFullNameField;
            }
            set
            {
                this.refFullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> refPhone
        {
            get
            {
                return this.refPhoneField;
            }
            set
            {
                this.refPhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string refTitle
        {
            get
            {
                return this.refTitleField;
            }
            set
            {
                this.refTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int referenceID
        {
            get
            {
                return this.referenceIDField;
            }
            set
            {
                this.referenceIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Question", Namespace="http://schemas.datacontract.org/2004/07/TrackableEntities.Models", IsReference=true)]
    public partial class Question : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private TrackableEntities.Models.ApplicantQuestionAnswer[] ApplicantQuestionAnswersField;
        
        private string[] ModifiedPropertiesField;
        
        private TrackableEntities.Models.QuestionInterviewQuestionMapping[] QuestionInterviewQuestionMappingsField;
        
        private TrackableEntities.Models.QuestionQuestionnaire[] QuestionQuestionnairesField;
        
        private TrackableEntities.TrackingState TrackingStateField;
        
        private int interviewQuestionsIDField;
        
        private string qAnswerStringField;
        
        private string qOptionStringField;
        
        private string qTextField;
        
        private string qTypeField;
        
        private int questionIDField;
        
        private System.Nullable<int> questionnaireIDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.Models.ApplicantQuestionAnswer[] ApplicantQuestionAnswers
        {
            get
            {
                return this.ApplicantQuestionAnswersField;
            }
            set
            {
                this.ApplicantQuestionAnswersField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ModifiedProperties
        {
            get
            {
                return this.ModifiedPropertiesField;
            }
            set
            {
                this.ModifiedPropertiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.Models.QuestionInterviewQuestionMapping[] QuestionInterviewQuestionMappings
        {
            get
            {
                return this.QuestionInterviewQuestionMappingsField;
            }
            set
            {
                this.QuestionInterviewQuestionMappingsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.Models.QuestionQuestionnaire[] QuestionQuestionnaires
        {
            get
            {
                return this.QuestionQuestionnairesField;
            }
            set
            {
                this.QuestionQuestionnairesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.TrackingState TrackingState
        {
            get
            {
                return this.TrackingStateField;
            }
            set
            {
                this.TrackingStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int interviewQuestionsID
        {
            get
            {
                return this.interviewQuestionsIDField;
            }
            set
            {
                this.interviewQuestionsIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string qAnswerString
        {
            get
            {
                return this.qAnswerStringField;
            }
            set
            {
                this.qAnswerStringField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string qOptionString
        {
            get
            {
                return this.qOptionStringField;
            }
            set
            {
                this.qOptionStringField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string qText
        {
            get
            {
                return this.qTextField;
            }
            set
            {
                this.qTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string qType
        {
            get
            {
                return this.qTypeField;
            }
            set
            {
                this.qTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int questionID
        {
            get
            {
                return this.questionIDField;
            }
            set
            {
                this.questionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> questionnaireID
        {
            get
            {
                return this.questionnaireIDField;
            }
            set
            {
                this.questionnaireIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuestionInterviewQuestionMapping", Namespace="http://schemas.datacontract.org/2004/07/TrackableEntities.Models", IsReference=true)]
    public partial class QuestionInterviewQuestionMapping : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private TrackableEntities.Models.InterviewQuestion InterviewQuestionField;
        
        private string[] ModifiedPropertiesField;
        
        private TrackableEntities.Models.Question QuestionField;
        
        private TrackableEntities.TrackingState TrackingStateField;
        
        private int interviewQuestionsIDField;
        
        private System.Nullable<int> numberOfQuestionsField;
        
        private int questionIDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.Models.InterviewQuestion InterviewQuestion
        {
            get
            {
                return this.InterviewQuestionField;
            }
            set
            {
                this.InterviewQuestionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ModifiedProperties
        {
            get
            {
                return this.ModifiedPropertiesField;
            }
            set
            {
                this.ModifiedPropertiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.Models.Question Question
        {
            get
            {
                return this.QuestionField;
            }
            set
            {
                this.QuestionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.TrackingState TrackingState
        {
            get
            {
                return this.TrackingStateField;
            }
            set
            {
                this.TrackingStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int interviewQuestionsID
        {
            get
            {
                return this.interviewQuestionsIDField;
            }
            set
            {
                this.interviewQuestionsIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> numberOfQuestions
        {
            get
            {
                return this.numberOfQuestionsField;
            }
            set
            {
                this.numberOfQuestionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int questionID
        {
            get
            {
                return this.questionIDField;
            }
            set
            {
                this.questionIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuestionQuestionnaire", Namespace="http://schemas.datacontract.org/2004/07/TrackableEntities.Models", IsReference=true)]
    public partial class QuestionQuestionnaire : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string[] ModifiedPropertiesField;
        
        private TrackableEntities.Models.Question QuestionField;
        
        private TrackableEntities.Models.Questionnaire QuestionnaireField;
        
        private TrackableEntities.TrackingState TrackingStateField;
        
        private System.Nullable<int> numberOfQuestionsField;
        
        private int questionIDField;
        
        private int questionnaireIDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ModifiedProperties
        {
            get
            {
                return this.ModifiedPropertiesField;
            }
            set
            {
                this.ModifiedPropertiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.Models.Question Question
        {
            get
            {
                return this.QuestionField;
            }
            set
            {
                this.QuestionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.Models.Questionnaire Questionnaire
        {
            get
            {
                return this.QuestionnaireField;
            }
            set
            {
                this.QuestionnaireField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.TrackingState TrackingState
        {
            get
            {
                return this.TrackingStateField;
            }
            set
            {
                this.TrackingStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> numberOfQuestions
        {
            get
            {
                return this.numberOfQuestionsField;
            }
            set
            {
                this.numberOfQuestionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int questionID
        {
            get
            {
                return this.questionIDField;
            }
            set
            {
                this.questionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int questionnaireID
        {
            get
            {
                return this.questionnaireIDField;
            }
            set
            {
                this.questionnaireIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InterviewQuestion", Namespace="http://schemas.datacontract.org/2004/07/TrackableEntities.Models", IsReference=true)]
    public partial class InterviewQuestion : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string[] ModifiedPropertiesField;
        
        private TrackableEntities.Models.QuestionInterviewQuestionMapping[] QuestionInterviewQuestionMappingsField;
        
        private TrackableEntities.TrackingState TrackingStateField;
        
        private int interviewQuestionsIDField;
        
        private int permissionsField;
        
        private System.Nullable<int> questionIDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ModifiedProperties
        {
            get
            {
                return this.ModifiedPropertiesField;
            }
            set
            {
                this.ModifiedPropertiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.Models.QuestionInterviewQuestionMapping[] QuestionInterviewQuestionMappings
        {
            get
            {
                return this.QuestionInterviewQuestionMappingsField;
            }
            set
            {
                this.QuestionInterviewQuestionMappingsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.TrackingState TrackingState
        {
            get
            {
                return this.TrackingStateField;
            }
            set
            {
                this.TrackingStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int interviewQuestionsID
        {
            get
            {
                return this.interviewQuestionsIDField;
            }
            set
            {
                this.interviewQuestionsIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int permissions
        {
            get
            {
                return this.permissionsField;
            }
            set
            {
                this.permissionsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> questionID
        {
            get
            {
                return this.questionIDField;
            }
            set
            {
                this.questionIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Questionnaire", Namespace="http://schemas.datacontract.org/2004/07/TrackableEntities.Models", IsReference=true)]
    public partial class Questionnaire : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private TrackableEntities.Models.Job[] JobsField;
        
        private string[] ModifiedPropertiesField;
        
        private TrackableEntities.Models.QuestionQuestionnaire[] QuestionQuestionnairesField;
        
        private TrackableEntities.TrackingState TrackingStateField;
        
        private System.Nullable<int> questionIDField;
        
        private int questionnaireIDField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.Models.Job[] Jobs
        {
            get
            {
                return this.JobsField;
            }
            set
            {
                this.JobsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ModifiedProperties
        {
            get
            {
                return this.ModifiedPropertiesField;
            }
            set
            {
                this.ModifiedPropertiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.Models.QuestionQuestionnaire[] QuestionQuestionnaires
        {
            get
            {
                return this.QuestionQuestionnairesField;
            }
            set
            {
                this.QuestionQuestionnairesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.TrackingState TrackingState
        {
            get
            {
                return this.TrackingStateField;
            }
            set
            {
                this.TrackingStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> questionID
        {
            get
            {
                return this.questionIDField;
            }
            set
            {
                this.questionIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int questionnaireID
        {
            get
            {
                return this.questionnaireIDField;
            }
            set
            {
                this.questionnaireIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Job", Namespace="http://schemas.datacontract.org/2004/07/TrackableEntities.Models", IsReference=true)]
    public partial class Job : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private TrackableEntities.Models.Application[] ApplicationsField;
        
        private TrackableEntities.Models.Employee[] EmployeesField;
        
        private TrackableEntities.Models.Hour HourField;
        
        private string[] ModifiedPropertiesField;
        
        private TrackableEntities.Models.Questionnaire QuestionnaireField;
        
        private TrackableEntities.TrackingState TrackingStateField;
        
        private string descriptionField;
        
        private string fullPartTimeField;
        
        private int jobIDField;
        
        private System.Nullable<int> operatingHoursIDField;
        
        private string positionField;
        
        private System.Nullable<int> questionnaireIDField;
        
        private string salaryRangeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.Models.Application[] Applications
        {
            get
            {
                return this.ApplicationsField;
            }
            set
            {
                this.ApplicationsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.Models.Employee[] Employees
        {
            get
            {
                return this.EmployeesField;
            }
            set
            {
                this.EmployeesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.Models.Hour Hour
        {
            get
            {
                return this.HourField;
            }
            set
            {
                this.HourField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] ModifiedProperties
        {
            get
            {
                return this.ModifiedPropertiesField;
            }
            set
            {
                this.ModifiedPropertiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.Models.Questionnaire Questionnaire
        {
            get
            {
                return this.QuestionnaireField;
            }
            set
            {
                this.QuestionnaireField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TrackableEntities.TrackingState TrackingState
        {
            get
            {
                return this.TrackingStateField;
            }
            set
            {
                this.TrackingStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fullPartTime
        {
            get
            {
                return this.fullPartTimeField;
            }
            set
            {
                this.fullPartTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int jobID
        {
            get
            {
                return this.jobIDField;
            }
            set
            {
                this.jobIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> operatingHoursID
        {
            get
            {
                return this.operatingHoursIDField;
            }
            set
            {
                this.operatingHoursIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string position
        {
            get
            {
                return this.positionField;
            }
            set
            {
                this.positionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> questionnaireID
        {
            get
            {
                return this.questionnaireIDField;
            }
            set
            {
                this.questionnaireIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string salaryRange
        {
            get
            {
                return this.salaryRangeField;
            }
            set
            {
                this.salaryRangeField = value;
            }
        }
    }
}
namespace TrackableEntities
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrackingState", Namespace="http://schemas.datacontract.org/2004/07/TrackableEntities")]
    public enum TrackingState : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unchanged = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Added = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Modified = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 3,
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="urn:trackable-entities:service", ConfigurationName="IUserService")]
public interface IUserService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IUserService/GetUsersList", ReplyAction="urn:trackable-entities:service/IUserService/GetUsersListResponse")]
    TrackableEntities.Models.User[] GetUsersList();
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IUserService/GetUsersList", ReplyAction="urn:trackable-entities:service/IUserService/GetUsersListResponse")]
    System.Threading.Tasks.Task<TrackableEntities.Models.User[]> GetUsersListAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IUserService/GetUser", ReplyAction="urn:trackable-entities:service/IUserService/GetUserResponse")]
    TrackableEntities.Models.User GetUser(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IUserService/GetUser", ReplyAction="urn:trackable-entities:service/IUserService/GetUserResponse")]
    System.Threading.Tasks.Task<TrackableEntities.Models.User> GetUserAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IUserService/UpdateUser", ReplyAction="urn:trackable-entities:service/IUserService/UpdateUserResponse")]
    TrackableEntities.Models.User UpdateUser(TrackableEntities.Models.User entity);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IUserService/UpdateUser", ReplyAction="urn:trackable-entities:service/IUserService/UpdateUserResponse")]
    System.Threading.Tasks.Task<TrackableEntities.Models.User> UpdateUserAsync(TrackableEntities.Models.User entity);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IUserService/CreateUser", ReplyAction="urn:trackable-entities:service/IUserService/CreateUserResponse")]
    TrackableEntities.Models.User CreateUser(TrackableEntities.Models.User entity);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IUserService/CreateUser", ReplyAction="urn:trackable-entities:service/IUserService/CreateUserResponse")]
    System.Threading.Tasks.Task<TrackableEntities.Models.User> CreateUserAsync(TrackableEntities.Models.User entity);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IUserService/DeleteUser", ReplyAction="urn:trackable-entities:service/IUserService/DeleteUserResponse")]
    bool DeleteUser(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IUserService/DeleteUser", ReplyAction="urn:trackable-entities:service/IUserService/DeleteUserResponse")]
    System.Threading.Tasks.Task<bool> DeleteUserAsync(int id);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IUserServiceChannel : IUserService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class UserServiceClient : System.ServiceModel.ClientBase<IUserService>, IUserService
{
    
    public UserServiceClient()
    {
    }
    
    public UserServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public TrackableEntities.Models.User[] GetUsersList()
    {
        return base.Channel.GetUsersList();
    }
    
    public System.Threading.Tasks.Task<TrackableEntities.Models.User[]> GetUsersListAsync()
    {
        return base.Channel.GetUsersListAsync();
    }
    
    public TrackableEntities.Models.User GetUser(int id)
    {
        return base.Channel.GetUser(id);
    }
    
    public System.Threading.Tasks.Task<TrackableEntities.Models.User> GetUserAsync(int id)
    {
        return base.Channel.GetUserAsync(id);
    }
    
    public TrackableEntities.Models.User UpdateUser(TrackableEntities.Models.User entity)
    {
        return base.Channel.UpdateUser(entity);
    }
    
    public System.Threading.Tasks.Task<TrackableEntities.Models.User> UpdateUserAsync(TrackableEntities.Models.User entity)
    {
        return base.Channel.UpdateUserAsync(entity);
    }
    
    public TrackableEntities.Models.User CreateUser(TrackableEntities.Models.User entity)
    {
        return base.Channel.CreateUser(entity);
    }
    
    public System.Threading.Tasks.Task<TrackableEntities.Models.User> CreateUserAsync(TrackableEntities.Models.User entity)
    {
        return base.Channel.CreateUserAsync(entity);
    }
    
    public bool DeleteUser(int id)
    {
        return base.Channel.DeleteUser(id);
    }
    
    public System.Threading.Tasks.Task<bool> DeleteUserAsync(int id)
    {
        return base.Channel.DeleteUserAsync(id);
    }
}
