//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIM.Web.Admin.UserServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:trackable-entities:service", ConfigurationName="UserServiceReference.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IUserService/GetUsersList", ReplyAction="urn:trackable-entities:service/IUserService/GetUsersListResponse")]
        AIM.Service.Entities.Models.User[] GetUsersList();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IUserService/GetUser", ReplyAction="urn:trackable-entities:service/IUserService/GetUserResponse")]
        AIM.Service.Entities.Models.User GetUser(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IUserService/UpdateUser", ReplyAction="urn:trackable-entities:service/IUserService/UpdateUserResponse")]
        AIM.Service.Entities.Models.User UpdateUser(AIM.Service.Entities.Models.User entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IUserService/CreateUser", ReplyAction="urn:trackable-entities:service/IUserService/CreateUserResponse")]
        AIM.Service.Entities.Models.User CreateUser(AIM.Service.Entities.Models.User entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IUserService/DeleteUser", ReplyAction="urn:trackable-entities:service/IUserService/DeleteUserResponse")]
        bool DeleteUser(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : AIM.Web.Admin.UserServiceReference.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<AIM.Web.Admin.UserServiceReference.IUserService>, AIM.Web.Admin.UserServiceReference.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AIM.Service.Entities.Models.User[] GetUsersList() {
            return base.Channel.GetUsersList();
        }
        
        public AIM.Service.Entities.Models.User GetUser(System.Nullable<int> id) {
            return base.Channel.GetUser(id);
        }
        
        public AIM.Service.Entities.Models.User UpdateUser(AIM.Service.Entities.Models.User entity) {
            return base.Channel.UpdateUser(entity);
        }
        
        public AIM.Service.Entities.Models.User CreateUser(AIM.Service.Entities.Models.User entity) {
            return base.Channel.CreateUser(entity);
        }
        
        public bool DeleteUser(int id) {
            return base.Channel.DeleteUser(id);
        }
    }
}
