//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIM.Web.Admin.PersonalInfoServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:trackable-entities:service", ConfigurationName="PersonalInfoServiceReference.IPersonalInfoService")]
    public interface IPersonalInfoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IPersonalInfoService/GetPersonalInfoList", ReplyAction="urn:trackable-entities:service/IPersonalInfoService/GetPersonalInfoListResponse")]
        AIM.Service.Entities.Models.PersonalInfo[] GetPersonalInfoList();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IPersonalInfoService/GetPersonalInfo", ReplyAction="urn:trackable-entities:service/IPersonalInfoService/GetPersonalInfoResponse")]
        AIM.Service.Entities.Models.PersonalInfo GetPersonalInfo(System.Nullable<int> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IPersonalInfoService/UpdatePersonalInfo", ReplyAction="urn:trackable-entities:service/IPersonalInfoService/UpdatePersonalInfoResponse")]
        AIM.Service.Entities.Models.PersonalInfo UpdatePersonalInfo(AIM.Service.Entities.Models.PersonalInfo entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IPersonalInfoService/CreatePersonalInfo", ReplyAction="urn:trackable-entities:service/IPersonalInfoService/CreatePersonalInfoResponse")]
        AIM.Service.Entities.Models.PersonalInfo CreatePersonalInfo(AIM.Service.Entities.Models.PersonalInfo entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:trackable-entities:service/IPersonalInfoService/DeletePersonalInfo", ReplyAction="urn:trackable-entities:service/IPersonalInfoService/DeletePersonalInfoResponse")]
        bool DeletePersonalInfo(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPersonalInfoServiceChannel : AIM.Web.Admin.PersonalInfoServiceReference.IPersonalInfoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersonalInfoServiceClient : System.ServiceModel.ClientBase<AIM.Web.Admin.PersonalInfoServiceReference.IPersonalInfoService>, AIM.Web.Admin.PersonalInfoServiceReference.IPersonalInfoService {
        
        public PersonalInfoServiceClient() {
        }
        
        public PersonalInfoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonalInfoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonalInfoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonalInfoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AIM.Service.Entities.Models.PersonalInfo[] GetPersonalInfoList() {
            return base.Channel.GetPersonalInfoList();
        }
        
        public AIM.Service.Entities.Models.PersonalInfo GetPersonalInfo(System.Nullable<int> id) {
            return base.Channel.GetPersonalInfo(id);
        }
        
        public AIM.Service.Entities.Models.PersonalInfo UpdatePersonalInfo(AIM.Service.Entities.Models.PersonalInfo entity) {
            return base.Channel.UpdatePersonalInfo(entity);
        }
        
        public AIM.Service.Entities.Models.PersonalInfo CreatePersonalInfo(AIM.Service.Entities.Models.PersonalInfo entity) {
            return base.Channel.CreatePersonalInfo(entity);
        }
        
        public bool DeletePersonalInfo(int id) {
            return base.Channel.DeletePersonalInfo(id);
        }
    }
}
